<?php

namespace AppBundle\Repository;

/**
 * AccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsRepository extends \Doctrine\ORM\EntityRepository
{
}
