<?php

namespace AppBundle\Repository;

/**
 * AccountTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
