<?php

namespace AppBundle\Repository;

/**
 * BanksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanksRepository extends \Doctrine\ORM\EntityRepository
{
}
