<?php

namespace AppBundle\Repository;

/**
 * CurrenciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrenciesRepository extends \Doctrine\ORM\EntityRepository
{
}
